### ISSUE TITLE
Migrate to Flutter

### ISSUE THREAD

**Issue by TeisAngel** [Vitaliy5/AndroidMemeShop#1]
I think, that this application is a great opportunity to try new technologies like Flutter.

**Comment by TeisAngel** [comment]
A couple of reasons why:

- Java bad
- Flutter good

**Comment by TeisAngel** [comment]
@Vitaliy5

**Comment by Vitalii-RD** [comment]
> A couple of reasons why:
> 
> * Java bad
> * Flutter good

@TeisAngel There are a couple of reasons why I won't do that:
1. Fuck you 
2. Suck my balls

On top of that, this app is meant for college, and I was not the one who decided the stack of technologies. 

P.S 
Thanks for your recommendations. Have a nice day

**Comment by Vitalii-RD** [comment]
This issue is settled

**Comment by TeisAngel** [comment]
I don't think that's a real stopper here. We all know, progress is inevitable.I think you will change your mind in the future. To make my point clear, here are some discussions about the same thing: [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO) and also [here](https://www.youtube.com/watch?v=ajnNdUImtCE)

**Comment by TeisAngel** [comment]
@Vitaliy5
