### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by TeisAngel** [Vitaliy5/AndroidMemeShop#2]
Haven't seen commits for the whole two days. That's quite a big gap in activity. 

**I this project still maintained?**

**Comment by Vitalii-RD** [comment]
> Haven't seen commits for the whole two days. That's quite a big gap in activity.
> 
> **I this project still maintained?**

@TeisAngel Do you think I am **insane or what**? I need breaks and I have other stuff to do besides this project, however, I continue to work on this project on my weekends, unfortunately :( 
If you have any propositions or recommendations regarding this project, feel free to go fuck yourself
P.S.
Thanks for checking on the project
